server:
  port: 8091

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8085/eureka/

spring:
  application:
    name: lol-hero

  main:
    allow-bean-definition-overriding: true

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/the_games
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  type-aliases-package: com.zy.common.entity
  mapper-locations: classpath:mybatis/mapper/*.xml